### PR TITLE
Reflect our lesson plan on the website.

### PR DESCRIPTION
**Pull request by bsmith89**
Update the website to reflect our current plan for lessons.

TODO:
-   [x] update the schedule, syllabus with Shell, Python, Git (#7, #8)
-   [x] remove SQL install from website (#9)
-   [x] split off a schedule for the "intermediate" room (#6)
-   [x] add a description of the difference between the two rooms.  Expected knowledge for "intermediate" students (#6)
-   [x] link to an etherpad for the "intermediate" room (#6)
-   [x] update the installation test scripts (#10)

### CODE REVIEW

**Comment by dotsdl** [comment]
@bsmith89 do you want some help with this? I've done this all before for other workshops, including one with a split room. I could probably knock this out pretty quick.

**Comment by bsmith89** [comment]
Go for it!

How will the pull request work with two people contributing to it?  I
haven't done that through GH before...

**Comment by dotsdl** [comment]
It's just a branch, and since you added me as a collaborator I can just push to this branch. One of us will occasionally have to deal with merge conflicts depending.

**Comment by bsmith89** [comment]
@dotsdl So we're aiming to merge this by, what, Wednesday evening?

Do you have any adjustments to the scope of this PR?  What _needs_ to be on the website first?

**Comment by dotsdl** [comment]
@bsmith89 we can leave it. I can get the other points knocked out before the end of the day today. Working on it now.

**Comment by dotsdl** [comment]
Mostly trying to figure out the scope of what we'll do for the intermediate lesson; starting from the [python-intermediate-mosquitoes](https://github.com/swcarpentry/python-intermediate-mosquitoes) lesson.

**Comment by bsmith89** [comment]
I think giving students a good idea of what they need to _already_ know will be the most important thing.  Besides that, the syllabus on the website doesn't need to match the material we teach beyond a first-approximation.

I'm hoping each of the intermediate instructors can draft a blurb to that effect.

**Comment by bsmith89** [comment]
I've started new etherpads for each of the rooms here:

http://pad.software-carpentry.org/2016-04-29-ucsf-room1

and

http://pad.software-carpentry.org/2016-04-29-ucsf-room2.

**Comment by dotsdl** [comment]
Agreed. Syllabus is done as far as I see it. Working on clear explanation for what is expected of intermediate learners.

**Comment by bsmith89** [comment]
Great.  Leave the test-script editing to me.  (#10)

**Comment by bsmith89** [comment]
Are there any hidden dependencies for the learners' installation?  Can I comment out more lines than I have in 5aa0e98 ?

I haven't edited the test scripts before.

**Comment by dotsdl** [comment]
@bsmith89 that's all we need, yeah. We need everything that's still there, so that item is done.

**Comment by bsmith89** [comment]
Okay, then I'm taking the etherpad item now.

**Comment by bsmith89** [comment]
In 0cccba7 you only added splits for the Python sections.  Are we ultimately going to do the same for shell/Git?  Is that part of this PR?

**Comment by dotsdl** [comment]
I don't think it's necessary, unless we are teaching different shell/git lessons in each room?

**Comment by bsmith89** [comment]
I thought we were, but that's up to @fu9ar.

**Comment by dotsdl** [comment]
I added a note for the difference in introductory and intermediate python; @fu9ar if you want to make our room completely intermediate, then we can change things accordingly. Thoughts?

**Comment by bsmith89** [comment]
This is great.  Shall we do a quick review/merge and then let Kevin add his blurbs as a second PR?

**Comment by dotsdl** [comment]
I think so. Looking everything over now.

**Comment by bsmith89** [comment]
I'm happy with everything.  I may make some minor changes to the layout (e.g. put both python syllabuses in the same column) and language, but this PR looks good as-is.

**Comment by dotsdl** [comment]
Looks good to me.

**Pull request merged**
